[build.cfg]
target = { value = "x86_64-unknown-none", condition = "cfg(feature = \"platform_mock_nostd\")" }

# [unstable]
# build-std = ["core", "compiler_builtins", "alloc"]
# build-std-features = ["compiler-builtins-mem"]