[package]
name = "litebox_platform_linux_kernel"
version = "0.1.0"
edition = "2024"

[features]
platform_snp = []

[build-dependencies]
bindgen = "0.71.0"

[dependencies]
buddy_system_allocator = { version = "0.11.0", default-features = false }
litebox = { path = "../litebox/", version = "0.1.0" }
