[package]
name = "litebox_platform_linux_kernel"
version = "0.1.0"
edition = "2021"

[features]
platform_snp = []

[build-dependencies]
bindgen = "0.71.0"

[dependencies]
litebox = { path = "../litebox/", version = "0.1.0" }
once_cell = { version = "1.20.3", default-features = false, features = ["alloc", "race"] }