[package]
name = "litebox_platform_multiplex"
version = "0.1.0"
edition = "2024"

[dependencies]
litebox = { path = "../litebox/", version = "0.1.0" }
litebox_platform_linux_userland = { path = "../litebox_platform_linux_userland/", version = "0.1.0", optional = true }
litebox_platform_mock_nostd = { path = "../litebox_platform_mock_nostd/", version = "0.1.0", optional = true }
once_cell = { version = "1.20.2", default-features = false, features = ["alloc", "race"] }

[features]
# default = ["platform_linux_userland"]
# chuqi: necessary to support multiplexing
default = []
platform_linux_userland = ["dep:litebox_platform_linux_userland"]
platform_mock_nostd = ["dep:litebox_platform_mock_nostd"]

[lints]
workspace = true
