[package]
name = "litebox_util_log_macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for litebox_util_log"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }

[lints]
workspace = true
