[package]
name = "litebox_platform_linux_userland"
version = "0.1.0"
edition = "2024"

[features]
unstable-testing = []

[dependencies]
libc = { version = "0.2.169", default-features = false }
litebox = { path = "../litebox/", version = "0.1.0" }
nix = { version = "0.29.0", default-features = false, features = ["fs", "ioctl", "mman", "signal"] }
seccompiler = "0.5.0"
crossbeam = "0.8.4"

[lints]
workspace = true
