[package]
name = "syscall_rewriter"
version = "0.1.0"
edition = "2024"

[dependencies]
capstone = { version = "0.12", features = ["full"] }
object = { version = "0.36.7", features = ["write"] }
anyhow = "1.0"
memmap2 = "0.9"

[lints]
workspace = true