[package]
name = "litebox_platform_windows_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
litebox = { path = "../litebox/", version = "0.1.0" }
litebox_common_linux = { path = "../litebox_common_linux", version = "0.1.0" }
spin = "0.9.8"
bitflags = "2.6.0"

[lints]
workspace = true
